# Generated by Django 4.2.5 on 2023-10-22 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_reader_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 7, 57, 40, 648726, tzinfo=datetime.timezone.utc)),
        ),
    ]
