# Generated by Django 4.2.5 on 2023-10-27 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_reader_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 7, 34, 56, 854374, tzinfo=datetime.timezone.utc)),
        ),
    ]
