# Generated by Django 4.2.5 on 2023-11-10 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_reader_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 6, 24, 34, 132555, tzinfo=datetime.timezone.utc)),
        ),
    ]
