# Generated by Django 4.2.5 on 2023-11-26 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_reader_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 14, 26, 26, 300697, tzinfo=datetime.timezone.utc)),
        ),
    ]
