# Generated by Django 4.2.5 on 2023-11-28 16:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_author_alter_book_title'),
        ('user', '0010_alter_reader_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 16, 10, 13, 109956, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('overall_reading_time', models.FloatField()),
                ('reread', models.BooleanField(default=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('reader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reader',
            name='books',
            field=models.ManyToManyField(through='user.ReadingList', to='book.book'),
        ),
    ]
