# Generated by Django 4.2.5 on 2023-12-13 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_reader_date_joined_readinglist_reader_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 11, 33, 53, 304447, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='finish_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='overall_reading_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
