# Generated by Django 5.0.1 on 2024-03-28 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_reader_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 11, 18, 38, 616943, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reader',
            name='password',
            field=models.CharField(max_length=40),
        ),
    ]
