# Generated by Django 4.2.5 on 2023-10-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='style',
            field=models.FilePathField(default='/book/static/book/book_styles/'),
        ),
    ]
