# Generated by Django 4.2.5 on 2023-10-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(upload_to='book_file/'),
        ),
    ]
